### ISSUE TITLE
worker encounters an out-of-memory (OOM)

### ISSUE THREAD

**Issue by KScaesar** [KScaesar/Spring-2023-MIT6.5840#1]
The worker encounters an out-of-memory (OOM) error when the reduce task attempts to 
read a large number of Intermediate files.
But reading a small number of files, everything functions correctly.

In the video, the scenario involves the following configuration: 
**kernel: Linux PE60-6QE 5.10.125-0510125-generic**
**os: Ubuntu 20.04.6 LTS**
**map tasks = 8, reduce tasks = 2, and worker = 1.**
`go run ./coordinator/mrcoordinator.go ./pg-*`
`go run ./worker/mrworker.go`

The map tasks are operating normally. 

However, when the reduce tasks are executed, they attempt to read from 8 files sequentially. 
The memory usage, as indicated by the htop utility, rapidly increases and even fills up the swap disk. 
Eventually, this leads to a worker program be killed.

![reduce issue](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/b992f16e-1a80-48f3-912d-1aa5cc3ad8df)

Intermediate file size
![image](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/cb536edb-b31e-403a-af7e-5cf489ca055e)

**Comment by KScaesar** [comment]
#Create a profiler using the [go test file](https://github.com/KScaesar/Spring-2023-MIT6.5840/blob/master/src/mr/task_test.go#L36).

## cpu profiler:
![image](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/56239ef0-7491-4593-8a12-ad2d711e0ef3)

## memory profiler:
![image](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/fd13b42c-1eeb-4286-a3df-7e80408174c5)

## root cause ??

I suspect the problem area is within the **doReducer** method. 
The memory usage seems to be highest during the execution of json.Unmarshal.

https://github.com/KScaesar/Spring-2023-MIT6.5840/blob/a214a8e480db86a8283d2311f18856e69eb02076/src/mr/task.go#L149-L190

**Comment by KScaesar** [comment]
# go tool trace

```shell
# test.binary (mr.test)
mr.test -test.v -test.run TestReduceTask_Exec -test.trace trace.out
```

---

```
go tool trace trace.out
```
![image](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/284c90d3-678a-4120-abce-17a3da5968c4)

---

```
go tool trace -pprof=syscall trace.out > syscall.pprof
go tool pprof syscall.pprof
```

![syscall pprof](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/283449e8-03cd-4f52-8022-35bd4952e26d)

---

```
go tool trace -pprof=sched trace.out > sched.pprof
go tool pprof sched.pprof
```

![sched pprof](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/0dd4229f-9677-4abc-bb00-e7283b5c9ad9)

**Comment by unknowntpo** [comment]
Even Map task won't work because you forget to unlock mutex in `Coordinator.AcquiredTask`
.
https://github.com/KScaesar/Spring-2023-MIT6.5840/blob/c35206b68ea2da2ec52e269f9b1e179799c097b9/src/mr/coordinator.go#L113-L115

**Comment by KScaesar** [comment]
#> Even Map task won't work because you forget to unlock mutex in `Coordinator.AcquiredTask` .
> 
> https://github.com/KScaesar/Spring-2023-MIT6.5840/blob/c35206b68ea2da2ec52e269f9b1e179799c097b9/src/mr/coordinator.go#L113-L115

refactor typo XD
![image](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/4e8e7819-72ec-43fc-8e47-f96d4cd9d4ee)

OOM問題是重構之前紀錄的
抱歉讓你誤會

**Comment by KScaesar** [comment]
## mem profiler

#root cause !!!!
`pairs[key] = append(pairs[key], values...) `

![image](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/6bc554ec-3b1e-4033-bd93-00e9f9e63063)
![image](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/15e78b25-11c4-41f9-8841-a762e3f2f2b9)

## source:
![image](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/e4d50dab-b6b9-4212-8045-3f6a397c3e73)
![image](https://github.com/KScaesar/Spring-2023-MIT6.5840/assets/29731683/868ed4dd-8d07-41c8-a993-0ffe3389f398)
